- hosts: all
  roles:
    - role: arubanetworks.aos_wlan_role
  tasks:
    - name: Creating a RADIUS server
      aos_api_config:
        method: POST
        config_path: /md/Boston
        data:
          - rad_server:
              - rad_server_name: test-server
                rad_host:
                  host: 1.1.1.1
