- name: Create and configure a BYOD SSID
  hosts: all
  roles:
    - role: arubanetworks.aos_wlan_role
  tasks:
    - name: Create a policy permitting access for BYOD clients to Captive Portal
      aos_api_config:
        method: POST
        config_path: /md/Boston
        data:
          - acl_sess:
              accname: mobilefirst-allow-captiveportal
              acl_sess__v4policy:
                - suser: true
                  src: suser
                  dipaddr: 1.1.1.1
                  dst: dhost
                  service-name: svc-http
                  svc: service-name
                  service_app: service
                  permit: true
                  action: permit
                - suser: true
                  src: suser
                  dipaddr: 1.1.1.1
                  dst: dhost
                  service-name: svc-https
                  svc: service-name
                  service_app: service
                  permit: true
                  action: permit
    - name: Create a policy to prevent BYOD clients from acting as a DHCP server
      aos_api_config:
        method: POST
        config_path: /md/Boston
        data:
          - acl_sess:
              accname: Mobilefirst-byod_employee-deny-client-as-dhcp-server
              acl_sess__v4policy:
                - suser: true
                  src: suser
                  dany: true
                  dst: dany
                  proto: udp
                  svc: tcp_udp
                  service_app: service
                  port1: 68
                  port: range
                  deny: true
                  action: deny_opt
              acl_sess__v6policy:
                - suser: true
                  src: suser
                  dany: true
                  dst: dany
                  rtr-adv: true
                  icmp_type: rtr-adv
                  svc: icmpv6
                  service_app: service
                  deny: true
                  action: deny_opt
    - name: Create a policy to allow all other traffic
      aos_api_config:
        method: POST
        config_path: /md/Boston
        data:
          - acl_sess:
              accname: Mobilefirst-byod_employee-allowall
              acl_sess__v4policy:
                - sany: true
                  src: sany
                  dany: true
                  dst: dany
                  service-any: true
                  svc: service-any
                  permit: true
                  action: permit
              acl_sess__v6policy:
                - sany: true
                  src: sany
                  dany: true
                  dst: dany
                  service-any: true
                  svc: service-any
                  service_app: service
                  permit: true
                  action: permit
    - name: Create a role named "onboard" and add appropriate ACLs
      aos_api_config:
        method: POST
        config_path: /md/Boston
        data:
          - role:
              rname: onboard
              role__acl:
                - acl_type: session
                  pname: mobilefirst-allow-captiveportal
                - acl_type: session
                  pname: logon-control
                - acl_type: session
                  pname: captiveportal
    - name: Create a role named "Mobilefirst-byod_employee" and add appropriate ACLs
      aos_api_config:
        method: POST
        config_path: /md/Boston
        data:
          - role:
              rname: Mobilefirst-byod_employee
              role__acl:
                - acl_type: session
                  pname: Mobilefirst-byod_employee-deny-client-as-dhcp-server
                - acl_type: session
                  pname: Mobilefirst-byod_employee-allowall
    - name: Create a RADIUS server
      aos_api_config:
        method: POST
        config_path: /md/Boston
        data:
          - rad_server:
              rad_server_name: CP-Corp-Server
              rad_host:
                host: 1.1.1.1
              rad_key:
                key: my-key-123
              rad_mac_delimiter:
                mba_delimiter_t: colon
    - name: Create a Server Group and add newly created RADIUS server
      aos_api_config:
        method: POST
        config_path: /md/Boston
        data:
          - server_group_prof:
              sg_name: CP-Corp-ServerGroup
              auth_server:
                - name: CP-Corp-Server
    - name: Define a RFC3576 Server
      aos_api_config:
        method: POST
        config_path: /md/Boston
        data:
          - rfc3576_client_prof:
              server_ip: 1.1.1.1
              rfc3576_secret:
                key: my-key-123
    - name: Define Dot1x Auth Profile
      aos_api_config:
        method: POST
        config_path: /md/Boston
        data:
          - dot1x_auth_profile:
              profile-name: MobileFirst-byod_employee_dot1x_auth_prof
    - name: Create AAA Profile
      aos_api_config:
        method: POST
        config_path: /md/Boston
        data:
          - aaa_prof:
              profile-name: MobileFirst-byod_employee_AAA_Prof
              default_user_role:
                role: onboard
              dot1x_auth_profile:
                profile-name: MobileFirst-byod_employee_dot1x_auth_prof
              dot1x_default_role:
                default-role: onboard
              dot1x_server_group:
                srv-group: CP-Corp-ServerGroup
              rad_acct_sg:
                server_group_name: CP-Corp-ServerGroup
              rfc3576_client:
                - rfc3576_server: 1.1.1.1
    - name: Create a Netdestination "google-play"
      aos_api_config:
        method: POST
        config_path: /md/Boston
        data:
          - netdst:
              dstname: google-play
              netdst__entry:
                - host_name: '*.ggpht.com'
                  _objname: netdst__name
                - host_name: '*.gstatic.com'
                  _objname: netdst__name
                - host_name: '*.android.clients.google.com'
                  _objname: netdst__name
                - host_name: '*.accounts.google.com'
                  _objname: netdst__name
                - host_name: '*.clients1.google.com'
                  _objname: netdst__name
                - host_name: '*.clients2.google.com'
                  _objname: netdst__name
                - host_name: '*.clients3.google.com'
                  _objname: netdst__name
                - host_name: '*.clients4.google.com'
                  _objname: netdst__name
                - host_name: '*.i.ytimg.com'
                  _objname: netdst__name
                - host_name: '*.google-analytics.com'
                  _objname: netdst__name
                - host_name: '*.android.l.google.com'
                  _objname: netdst__name
                - host_name: '*.mtalk.google.com'
                  _objname: netdst__name
                - host_name: '*.clients.l.google.com'
                  _objname: netdst__name
                - host_name: '*.googleapis.com'
                  _objname: netdst__name
                - host_name: '*.play.google.com'
                  _objname: netdst__name
                - host_name: '*.1e100.net'
                  _objname: netdst__name
                - host_name: '*.gvt1.com'
                  _objname: netdst__name
                - host_name: '*.l.googleusercontent.com'
                  _objname: netdst__name
                - host_name: '*.ggpht.net'
                  _objname: netdst__name
                - host_name: android.clients.google.com
                  _objname: netdst__name
                - host_name: ggpht.com
                  _objname: netdst__name
                - host_name: gstatic.com
                  _objname: netdst__name
                - host_name: accounts.google.com
                  _objname: netdst__name
                - host_name: clients1.google.com
                  _objname: netdst__name
                - host_name: clients2.google.com
                  _objname: netdst__name
                - host_name: clients3.google.com
                  _objname: netdst__name
                - host_name: clients4.google.com
                  _objname: netdst__name
                - host_name: i.ytimg.com
                  _objname: netdst__name
                - host_name: google-analytics.com
                  _objname: netdst__name
                - host_name: android.l.google.com
                  _objname: netdst__name
                - host_name: mtalk.google.com
                  _objname: netdst__name
                - host_name: clients.l.google.com
                  _objname: netdst__name
                - host_name: googleapis.com
                  _objname: netdst__name
                - host_name: play.google.com
                  _objname: netdst__name
                - host_name: 1e100.net
                  _objname: netdst__name
                - host_name: gvt1.com
                  _objname: netdst__name
                - host_name: l.googleusercontent.com
                  _objname: netdst__name
                - host_name: ggpht.net
                  _objname: netdst__name
    - name: Create Captive Portal Profile
      aos_api_config:
        method: POST
        config_path: /md/Boston
        data:
          - cp_auth_profile:
              profile-name: MobileFirst-onboard
              cp_default_role:
                default-role: onboard
              cp_server_group:
                server-group: CP-Corp-ServerGroup
              cp_redirect_pause:
                redirect-pause: 3
              cp_login_location:
                login-page: >-
                  https://cp-corp123.aruba-tme.com/onboard/byod_employee_onboard.php
              cp_welcome_location:
                welcome-page: /auth/welcome.html
              cp_white_list:
                - white-list: google-play
              url_hash_key:
                url-hash-key: xxxxx
    - name: Create a SSID Profile
      aos_api_config:
        method: POST
        config_path: /md/Boston
        data:
          - ssid_prof:
              profile-name: MobileFirst-byod_employee
              essid:
                essid: TME-MobileFirst-byod_employee
              opmode:
                wpa2-aes: true
    - name: Create a Virtual AP Profile
      aos_api_config:
        method: POST
        config_path: /md/Boston
        data:
          - virtual_ap:
              profile-name: MobileFirst-byod_employee
              aaa_prof:
                profile-name: MobileFirst-byod_employee_AAA_Prof
              ssid_prof:
                profile-name: MobileFirst-byod_employee
              vlan:
                vlan: '18'
    - name: Create an AP Group
      aos_api_config:
        method: POST
        config_path: /md/Boston
        data:
          - ap_group:
              profile-name: CampusAP
              virtual_ap:
                - profile-name: MobileFirst-byod_employee
